spring:
  application:
    name: CashBalanceService
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    out-of-order: true
    baseline-on-migrate: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: balance-update-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "yuriy.dev.cashbalanceservice.dto"
        spring.json.type.mapping: dealDto:yuriy.dev.cashbalanceservice.dto.DealDto,exchangeRateDto:yuriy.dev.cashbalanceservice.dto.ExchangeRateDto
      auto-offset-reset: earliest

server:
  port: 8083
