spring:
  application:
    name: ExchangeService
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    out-of-order: true
    baseline-on-migrate: true
server:
  port: 8081

token:
  signing:
    key: ${KEY}

